/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from '@react-three/drei'
import type {Mesh} from 'three'
import type {GLTF} from 'three-stdlib'
import {ConvexHullCollider} from '~/ecs/physics'
import type {ConvexHullColliderProps} from '~/ecs/physics'

type GLTFResult = GLTF & {
  nodes: {
    Ramp: Mesh
  }
  materials: Record<string, never>
}

type RampProps = Omit<ConvexHullColliderProps, 'args'>

export default function Ramp(props: RampProps) {
  const {nodes} = useGLTF('/ramp.glb') as unknown as GLTFResult
  const {geometry} = nodes.Ramp
  const vertices = geometry.attributes.position!.array as Float32Array

  return (
    <ConvexHullCollider args={[vertices]} {...props}>
      <mesh castShadow receiveShadow geometry={geometry}>
        <meshPhongMaterial color={0xfffff0} />
      </mesh>
    </ConvexHullCollider>
  )
}

useGLTF.preload('/ramp.glb')
