/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from '@react-three/drei'
import type {Mesh, MeshStandardMaterial} from 'three'
import type {GLTF} from 'three-stdlib'
import type {ECSConvexHullColliderProps} from '~/ecs/physics'
import {ECSConvexHullCollider} from '~/ecs/physics'

type GLTFResult = GLTF & {
  nodes: {
    Slope: Mesh
  }
  materials: {
    Slope: MeshStandardMaterial
  }
}

export default function Slope(props: Omit<ECSConvexHullColliderProps, 'args'>) {
  const {nodes} = useGLTF('/slope.glb') as GLTFResult
  const {geometry} = nodes.Slope
  const vertices = geometry.attributes.position.array as Float32Array

  return (
    <ECSConvexHullCollider args={[vertices]} {...props}>
      <mesh castShadow receiveShadow geometry={geometry}>
        <meshPhongMaterial color={0xed7200} />
      </mesh>
    </ECSConvexHullCollider>
  )
}

useGLTF.preload('/slope.glb')
