/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from '@react-three/drei'
import type {Mesh, MeshStandardMaterial} from 'three'
import type {GLTF} from 'three-stdlib'
import {ConvexHullCollider} from '~/ecs/physics'
import type {ConvexHullColliderProps} from '~/ecs/physics'

type GLTFResult = GLTF & {
  nodes: {
    Stone: Mesh
  }
  materials: {
    Stone: MeshStandardMaterial
  }
}

type StoneProps = Omit<ConvexHullColliderProps, 'args'>

export default function Stone({density = 4, ...props}: StoneProps) {
  const {nodes} = useGLTF('/stone.glb') as unknown as GLTFResult
  const {geometry} = nodes.Stone
  const vertices = geometry.attributes.position!.array as Float32Array

  return (
    <ConvexHullCollider args={[vertices]} density={density} {...props}>
      <mesh castShadow receiveShadow geometry={geometry}>
        <meshStandardMaterial color={0x625b4e} roughness={0.9} metalness={0} />
      </mesh>
    </ConvexHullCollider>
  )
}

useGLTF.preload('/stone.glb')
