/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Building(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/four-story-building.gltf");

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021.geometry}
        material={materials.Windows}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_1.geometry}
        material={materials.Glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_2.geometry}
        material={materials.Bricks}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_3.geometry}
        material={materials.Main}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_4.geometry}
        material={materials.Dark}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_5.geometry}
        material={materials.White}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube021_6.geometry}
        material={materials.Black}
      />
    </group>
  );
}

useGLTF.preload("/four-story-building.gltf");
