/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Car(props) {
  const group = useRef();
  const { nodes } = useGLTF("/car.glb");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2001.geometry}
        material={nodes.Object_2001.material}
        position={[0.1, 0.52, 0.63]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6001.geometry}
        material={nodes.Object_6001.material}
        position={[1.01, 0.17, 2.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_7001.geometry}
        material={nodes.Object_7001.material}
        position={[-0.9, 0.17, 1.97]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8001.geometry}
        material={nodes.Object_8001.material}
        position={[1.11, 0.17, -0.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_9001.geometry}
        material={nodes.Object_9001.material}
        position={[-0.81, 0.17, -0.59]}
      />
    </group>
  );
}
